// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydmfmcbdrweidqevjpbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbWZtY2JkcndlaWRxZXZqcGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDA3MDUsImV4cCI6MjA2NTk3NjcwNX0.MuPRT9FyDiXyWovDyuog3mobQNTboEMzc8tPaznqYu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);